services:
  wakapi:
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      # See README.md and config.default.yml for all config options
      WAKAPI_DB_TYPE: "postgres"
      WAKAPI_DB_NAME: "wakapi"
      WAKAPI_DB_USER: "wakapi"
      WAKAPI_DB_PASSWORD: "choose-a-password"
      WAKAPI_DB_HOST: "db"
      WAKAPI_DB_PORT: "5432"
      ENVIRONMENT: "prod"
      WAKAPI_PASSWORD_SALT_FILE: "/run/secrets/password_salt"
      WAKAPI_MAIL_SMTP_PASS_FILE: "/run/secrets/smtp_pass"
    secrets:
      - password_salt
      - smtp_pass

  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: "wakapi"
      POSTGRES_PASSWORD: "choose-a-password"
      POSTGRES_DB: "wakapi"
    volumes:
      - wakapi-db-data:/var/lib/postgresql/data

secrets:
  password_salt:
    environment: PASSWORD_SALT
  smtp_pass:
    environment: SMTP_PASS

volumes:
  wakapi-db-data: {}
