env: dev
app:
  custom_languages:
    jsx: JSX
    vue: Vue
    abc: Fooscript
security:
  password_salt:
  insecure_cookies: false
  cookie_max_age: 172800
db:
  host: localhost
  port: 5432
  user: wakapi_user
  password: wakapi
  name: wakapi_local
  dialect: postgres
  max_conn: 2
server:
  port: 3000
  listen_ipv4: 127.0.0.1
  base_path: /
